name: ci

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: node-24
    name: build
    steps:
      - uses: actions/checkout@v6

      - name: build
        uses: ./.forgejo/actions/build
        with:
          upload-artifacts: false
