name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: docker
    name: build
    steps:
      - uses: actions/checkout@v6

      - name: build
        uses: ./.forgejo/actions/build
        with:
          upload-artifacts: true
