name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Release tag, in the format /v\\d+.\\d+.\\d+/, e.g. v1.2.3"
        required: true
        type: string

      dontSign:
        description: "Skip AMO signing"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: node-24
    name: build
    steps:
      - uses: actions/checkout@v6

      - name: build
        uses: ./.forgejo/actions/build
        with:
          upload-artifacts: true

  release-server:
    runs-on: ubuntu-24
    steps:
      - uses: actions/checkout@v6

      - name: build and push
        run: |
          set -x
          echo  ${{ secrets.RELEASE_TOKEN }} | docker login git.goisser.net -u benjamin --password-stdin
          docker compose build --push

  release:
    runs-on: node-24
    needs: 
      - build
      - release-server
    env:
      RELEASE_TAG: ${{ inputs.releaseTag || forgejo.ref_name }}
    steps:
      - uses: forgejo/download-artifact@v4
        with:
          name: klo-client
          path: artifacts/

      - uses: forgejo/download-artifact@v4
        with:
          name: klo-server
          path: artifacts/

      - uses: actions/checkout@v6
        with:
          path: ${{ forgejo.workspace }}/repo

      - name: prepare release dir
        run: |
          mkdir -p release
          mv artifacts/klo-server.zip release/klo-server-${{ env.RELEASE_TAG }}.zip

      - name: sign extension
        if: ${{ !inputs.dontSign }}
        run: |
          set -x

          npm i -g web-ext

          ls -lAh
          ls -lAh artifacts
          ls -lAh repo

          unzip artifacts/klo-client.zip -d dist

          ls -lAh dist

          web-ext sign                                                \
            -s dist                                                   \
            -a .                                                      \
            --upload-source-code artifacts/klo-client.zip             \
            --amo-metadata repo/client/amo-metadata.json              \
            --channel unlisted                                        \
            --timeout 1800000                                         \
            --api-key "${{ secrets.MOZ_API_KEY }}"                    \
            --api-secret "${{ secrets.MOZ_API_SECRET }}"

          mv *.xpi "release/klo-client-${{ env.RELEASE_TAG }}.xpi"

          ls -lAh
          ls -lAh release

          curl                                                                                                                                 \
            -X PUT                                                                                                                             \
            -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}"                                                                             \
            -v https://git.goisser.net/api/packages/Benjamin/generic/klo-client/${{ env.RELEASE_TAG }}/klo-client-${{ env.RELEASE_TAG }}.xpi \
            -T release/klo-client-${{ env.RELEASE_TAG }}.xpi

      - name: parse changelog
        id: parse_changelog
        run: |
          set -x
          changelog=`perl -0777 -ne 'if (/(?<=## ${{ env.RELEASE_TAG }}\n\n)[\S\s]+?(?=\n\n##|\z)/m) { print "$&\n"; }' repo/CHANGELOG.md`
          echo "$changelog"
          echo "changelog<<EOF" >> $FORGEJO_OUTPUT
          echo "$changelog" >> $FORGEJO_OUTPUT
          echo "EOF" >> $FORGEJO_OUTPUT

      - uses: https://code.forgejo.org/actions/forgejo-release@v2.7.3
        with:
          direction: upload
          url: https://git.goisser.net
          repo: Benjamin/klo
          token: ${{ secrets.RELEASE_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          release-dir: release/
          release-notes: "${{ steps.parse_changelog.outputs.changelog }}"
          prerelease: true
